import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { defineConfig, loadEnv, type Plugin } from "vite";
import react from "@vitejs/plugin-react";

// phase-05-local-playable.md "PWA foundation": a service worker that
// precaches the build. Hand-rolled rather than a workbox-based generator
// (docs/DECISIONS.md ADR-012) — the whole build's asset list is small and
// this keeps every emitted file something a human can actually read end to
// end. The manifest and icons are generated separately, by
// scripts/generate-manifest.ts (run via `tsx` before `dev`/`build` —
// see package.json): unlike this plugin, that script needs to import
// @veilbreak/content for GAME_TITLE, which Vite's own config-loading step
// can't resolve (ADR-012's second decision) — this plugin only needs the
// final build's own emitted file names, so it stays free of that problem.
function veilbreakServiceWorkerPlugin(): Plugin {
  return {
    name: "veilbreak-service-worker",
    generateBundle(_options, bundle) {
      const emittedUrls = Object.keys(bundle)
        .filter((fileName) => !fileName.endsWith(".map"))
        .map((fileName) => `./${fileName}`);
      // manifest.webmanifest and the icons live in public/ (generated by
      // scripts/generate-manifest.ts), so Vite copies them straight through
      // rather than passing them through this hook's `bundle` — added here
      // by their known, fixed names instead. index.html is also missing
      // from `bundle` at this point (Vite's own HTML-handling plugin runs
      // its generateBundle after this one, so it hasn't added its asset
      // yet) — without it, an offline reload of "/" would have nothing to
      // serve. "./" is cached as its own key too, since a navigation
      // request's URL is the origin/scope root, not literally "index.html".
      const precacheUrls = [
        ...emittedUrls,
        "./",
        "./index.html",
        "./manifest.webmanifest",
        "./icons/icon-192.svg",
        "./icons/icon-512.svg",
      ];

      const swTemplatePath = fileURLToPath(new URL("./sw-template.js", import.meta.url));
      const swTemplate = readFileSync(swTemplatePath, "utf8");
      // A real per-build id (not a fixed literal) so `activate`'s cleanup
      // actually removes the previous build's cache instead of leaving it
      // to accumulate forever under the same never-changing cache name.
      const swSource = swTemplate
        .replace("__CACHE_VERSION__", String(Date.now()))
        .replace('"__PRECACHE_URLS__"', JSON.stringify(precacheUrls));
      this.emitFile({ type: "asset", fileName: "sw.js", source: swSource });
    },
  };
}

// Relative base (CLAUDE.md "client-only"): the build output must work when
// served from any static host, including a subpath or a local file, with no
// server-side rewriting.
// phase-12: developer mode (balance workbench, simulation dashboard) is compiled
// in only for dev builds, or when a build is made on purpose with
// VITE_DEV_MODE=1. In a normal production build both flags are the literal
// `false`, so the dev entry point (and everything only it imports) is dropped
// by tree-shaking; scripts/verify-no-dev-mode.mjs checks that in CI.
// ADR-040: `vite build --mode single` makes one self-contained page that works when opened
// straight from disk (no server): one JavaScript chunk, fonts inlined as data, the bot's
// worker inlined as a blob, no service worker. scripts/inline-single-file.mjs then folds the
// result into a single .html file.
export default defineConfig(({ mode }) => {
  const single = mode === "single";
  const forced = loadEnv(mode, process.cwd(), "VITE_").VITE_DEV_MODE === "1";
  return {
  define: {
    __DEV_TOOLS__: JSON.stringify((mode !== "production" && !single) || forced),
    __DEV_TOOLS_FORCED__: JSON.stringify(forced),
    __SINGLE_FILE__: JSON.stringify(single),
  },
  base: "./",
  plugins: single ? [react()] : [react(), veilbreakServiceWorkerPlugin()],
  worker: single ? { format: "iife" } : undefined,
  build: {
    outDir: single ? "dist-single" : "dist",
    ...(single ? { assetsInlineLimit: 100_000_000, cssCodeSplit: false } : {}),
    // Vite's default modulepreload polyfill calls fetch() (same-origin, to
    // prefetch a CSS/JS chunk) as a fallback for browsers without native
    // `<link rel="modulepreload">` support. That fetch is harmless (it never
    // leaves the static host), but scripts/verify-client-only.mjs can't
    // distinguish "same-origin fetch" from "fetch to a third party" through
    // static analysis, and this app doesn't need the prefetch optimization
    // yet. Disabling it keeps the guard's "no fetch/XHR/WebSocket in our
    // code" rule literal instead of growing a same-origin-detection carve-out.
    modulePreload: false,
    rollupOptions: {
      output: {
        // Isolates third-party library code (React) into its own chunk, so
        // scripts/verify-client-only.mjs can hold the app's own code to the
        // full client-only standard while treating vendor internals as
        // separately-audited (see that script's VENDOR_CHUNK_PATTERN
        // comment) rather than pattern-matching strings inside a framework
        // we don't control, like React-DOM's SVG/MathML namespace URIs.
        // Every third-party module lives in the "vendor" chunk (React, plus phase
        // 09's qrcode, jsqr and fflate and their dependencies), which
        // scripts/verify-client-only.mjs audits by hand instead of scanning.
        // Audited: qrcode's SVG writer embeds the W3C xmlns identifier (never
        // fetched); jsqr and fflate contain no URLs.
        ...(single ? { inlineDynamicImports: true } : { manualChunks(id: string) {
          return id.includes("node_modules") ? "vendor" : undefined;
        } }),
      },
    },
  },
  // These are internal workspace packages consumed as raw TypeScript source
  // (ADR-003, docs/DECISIONS.md), not pre-built npm dependencies. Excluding
  // them from Vite's dependency pre-bundling means dev-server edits inside
  // packages/* are picked up on every request instead of only after a
  // pre-bundle cache invalidation.
  optimizeDeps: {
    exclude: ["@veilbreak/content", "@veilbreak/engine", "@veilbreak/ai", "@veilbreak/persistence", "@veilbreak/protocol"],
  },
  };
});
