// packages/persistence: IndexedDB storage, the versioned local profile with
// migrations, atomic saves with rolling backups, JSON backup, device-transfer
// and replay codes, and QR rendering/decoding (spec/06 "Persistence and
// profile"). Runs entirely in the browser; no network.
export { createBestStore, createIndexedDbStore, createMemoryStore, type KeyValueStore } from "./store";
export {
  MAX_HISTORY,
  MIGRATIONS,
  PROFILE_VERSION,
  createDefaultProfile,
  historyEntrySchema,
  levelForXp,
  levelProgress,
  migrateProfile,
  parseProfile,
  profileSchema,
  settingsSchema,
  summarizeProfile,
  type Discovery,
  type HistoryEntry,
  type ParseResult,
  type Profile,
  type ProfileSummary,
  type Settings,
  type TeamPreset,
} from "./profile";
export {
  APEX_DIVISION,
  DEMOTION_BUFFER,
  DIVISIONS,
  K_PLACEMENT,
  K_RANKED,
  MAX_PAST_SEASONS,
  MAX_RECENT,
  PLACEMENT_CEILING,
  PLACEMENT_MATCHES,
  RANKED_START_RATING,
  applyRankedMatch,
  beginRankedMatch,
  createRanked,
  divisionIndexFor,
  expectedPermille,
  forfeitUnfinished,
  isPlaced,
  matchmakingDivision,
  rankedSchema,
  ratingChange,
  rollSeason,
  seasonIdFor,
  seasonStartRating,
  settleDivision,
  shownDivision,
  standing,
  usageRanking,
  type Division,
  type PendingRankedMatch,
  type RankedChange,
  type RankedMatchInput,
  type RankedMatchRecord,
  type RankedResult,
  type RankedState,
  type Rollover,
  type SeasonSummary,
} from "./ranked";
export { BACKUP_KEYS, SAVE_KEY, loadProfile, saveProfile, type LoadResult, type LoadSource, type SaveOptions } from "./save";
export {
  MAX_BACKUP_BYTES,
  MAX_REPLAY_LINK_CHARS,
  QR_MAX_BYTES,
  REPLAY_PREFIX,
  TRANSFER_PREFIX,
  decodeReplay,
  decodeTransfer,
  encodeReplay,
  encodeTransfer,
  packCode,
  unpackCode,
  exportBackup,
  extractTransferCode,
  importBackup,
  parseReplayFile,
  replayFileText,
  transferLink,
  type ImportResult,
  type ReplayDecode,
  type TransferResult,
} from "./codec";
export { MAX_STORED_REPLAYS, listReplays, loadReplay, replayRecordSchema, saveReplay, type ReplayRecord } from "./replay";
export { decodeQr, qrMatrix, renderQrRgba, renderQrSvg, type QrMatrix, type RgbaImage } from "./qr";
export { checksumOf, crc32 } from "./bytes";
